apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  role: arn:aws:iam::290913681714:role/eksctl-devops82-addon-iamserviceaccount-flux-external-secrets
  refreshInterval: 1m
  secretStoreRef:
    name: example-store
    kind: ClusterSecretStore
  target:
    name: prod-test-secret
    creationPolicy: Owner
  data:
  - secretKey: key1
    remoteRef:
      key: prod-test
      property: key1