apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example-store
    kind: SecretStore
  target:
    name: prod-test-secret
    creationPolicy: Owner
  data:
  - secretKey: key1
    remoteRef:
      key: prod-test
      property: key1