apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      role: external-secrets
      namespace: external-secrets
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key