apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
secretGenerator:
  - name: prod-secrets-env
    envs:
    - secrets/env-prod-secrets.env
    options:
      disableNameSuffixHash: true
