apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-sync
  namespace: flux-system
spec:
  targetNamespace: webapi6
  interval: 1m0s
  path: ./security/sops-kms-env
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: secretrepo
  decryption:
    provider: sops