apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: devrepo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitops-dev-auth
  timeout: 60s
  url: ssh://git@github.com/anakhub/gitops-dev-repo
