apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webapi6
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./applications/app2/app2.yaml
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: devrepo
