apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webapi6
  namespace: flux-system
spec:
  targetNamespace: webapi6
  interval: 1m0s
  path: ./applications/app2
  # path: ./clusters/default/applications/app2
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: devrepo
  patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webapi6
        namespace: webapi6
        annotations:
          secret.reloader.stakater.com/reload: "webapi6-config"
    target:
      kind: Deployment
      name: webapi6
      namespace: webapi6
  images:
  - name: 290913681714.dkr.ecr.ap-southeast-1.amazonaws.com/gitops/testwebapi6:amd64
    newName: docker.io
    newTag: prod-2
