apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webapi6
  namespace: flux-system
spec:
  targetNamespace: webapi6
  interval: 1m0s
  path: ./applications/app2
  # path: ./clusters/default/applications/app2
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: devrepo
